# Generated by Django 4.2 on 2025-03-01 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('estat', models.CharField(default='pendent', max_length=20)),
                ('preu_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProducteComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producte_id', models.IntegerField()),
                ('quantitat', models.IntegerField()),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.comanda')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
